Adds a role to configure VGPUS (#2)
* Initial commit of vgpu role

* Fix linting failures

* Whitespace fixes

* Reformat code

* Add README

* Include link to download software

* Remove broken table

* Fix typo

* Add DKMS flag

* Add reboot after driver install

This is a bit of a hammer, but without I was seeing:

```
Error: Parent 0000:21:00.4 is not currently registered for mdev support
```

* Apply suggestions from code review

* Add support for legacy time-sliced configuration

* Address review comments

* Fix url download

* Apply suggestions from code review

Co-authored-by: Mark Goddard <mark@stackhpc.com>

* Apply suggestions from code review

* Remove config.yml

* Apply suggestions from code review

* Fix startup ordering in non-mig mode

In MIG mode, waiting for nvidia-mig-manager ensure that sriov was enabled. In non-mig mode we need to explitly wait for this service to start.

* Remove remnants of old files

---------

Co-authored-by: Mark Goddard <mark@stackhpc.com>